name: photomem-laravel
recipe: laravel
config:
  webroot: public/
services:
  node:
    type: node:12
    build:
      - npm install
    run_as_root:
      - apt-get install imagemagick
      - ln -snf /usr/share/zoneinfo/America/Chicago /etc/localtime
      - echo "America/Chicago" > /etc/timezone
tooling:
  npm:
    service: node
  node:
    service: node
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd: /app/vendor/bin/phpunit
