name: photomem
recipe: laravel
config:
  webroot: public/
services:
  appserver:
    type: php:8.1
  node:
    type: node
    build:
      - npm install
    run_as_root:
      - apt-get update
      - apt-get install imagemagick
      - apt-get install -y python3 python3-pip
      - python3 -m pip install pillow
tooling:
  npm:
    service: node
  node:
    service: node
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd: /app/vendor/bin/phpunit
