version: '3'
# define all services
services:
  # our service is called laravel ;-)
  laravel:
    image: 'photomem'
    # we want to use the image which is build from our Dockerfile
    build: .
    # apache is running on port 80 but we want to expose this to port 1212 on our local machine
    ports:
      - "1212:80"
    volumes:
      - ./:/var/www/html
#    command: composer install
#    command: php artisan migrate

#services:
#  web:
#    environment:
#    - APACHE_RUN_USER=#1000
#    build:
#      context: ./docker/web
#    ports:
#    - 1212:80
#    volumes:
#    - ./:/var/www/html
