version: '3'
# define all services
services:
  # our service is called laravel ;-)
  laravel:
    image: php-laravel:latest
    # we want to use the image which is build from our Dockerfile
    build: .
    # apache is running on port 80 but we want to expose this to port 1212 on our local machine
    ports:
      - "1212:80"
    volumes:
      - ./:/var/www/html

  # for running sync jobs
  php-queue:
    restart: always
    image: php-laravel:latest
    command: php artisan queue:work
    volumes:
        - ./:/var/www/html/

#  db:
#    image: linuxserver/mariadb:latest
#    restart: always
#    environment: 
#      MYSQL_DATABASE: laravel
#      MYSQL_ALLOW_EMPTY_PASSWORD: 1
#    volumes:
#      - ./data:/var/lib/mysql
#    ports: 
#      - 33061:3306
